
version: '3'

# Setup from
# https://threedots.tech/post/go-docker-dev-environment-with-go-modules-and-live-code-reloading/

services:
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./redis:/usr/local/etc/redis:ro # for redis.conf
      - ./redis:/data # for dump.rdb
    ports:
      - "6739"
  server:
    build: ./server
    working_dir: /var/server
    container_name: server
    volumes:
     - ./server:/var/server:ro
     - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache # This allows you to share your gopkg cache with the container
     # well, it's supposed to, didn't work for me.
    environment:
      - SR_REDIS_URL=redis://redis:6379
    ports:
     - "3001:3001"
    entrypoint: reflex -sr .*.go -d none go run main/main.go
  # Remember, this needs to be rebuilt whenever packages change!
  web:
    build: ./web
    container_name: web
    volumes:
      - ./web/src:/var/code/src:ro
      - ./web/public/:/var/code/public:ro
    environment:
    ports:
      - "3000:3000"
