# canonical 'base' version - development override = .override.yml, prod override = .prod.yml

version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ../redis:/usr/local/etc/redis # for redis.conf, which redis wants to be editable
      - ../data/redis:/data # for dump.rdb
    user: 1000:1000
    networks:
      - redis
    ports:
      - "6379:6379"
  server:
    container_name: "server"
    # Build depends on dev or prod
    environment:
      - SR_REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - redis
      - backend
    ports:
      - "3001:3001"
  # No frontend/web defined here.

networks:
  redis:
  backend:
  frontend:
