name: Build

on:
  pull_request:
    paths:
      - 'web/**'

jobs:
  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v1
    - name: Run npm ci
      run: npm ci
    - name: Test
      run: npm test
    - name: Coverage
      run: npm run coverage
