name: Build

on: [ pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v1
    - name: Typecheck
      run: tsc
    - name: Test
      run: npm run test
    - name: Coverage
      run: npm run coverage
