name: Server

on:
  pull_request:
    paths:
      - 'server/**'

jobs:
  fmt-server:
    name: gofmt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.2'
    - name: List misformatted files
      run: gofmt -l .
    - name: Error if there are misformatted files
      run: test -z $(go fmt -l .)
  build-server:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.2'
    - name: Run go build
      run: go build -v -o out/sr-server ./main
    - name: Test
      run: go test -v ./...
