name: Frontend

on:
  pull_request:
    paths:
      - 'web/**'

jobs:
  build-web:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install
      run: npm ci
    - name: Test
      run: npm test
    - name: Confirm Build
      run: npm run build
    - name: Type Coverage
      run: npm run coverage
